#!/usr/bin/env sh
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
case "$BRANCH" in
  main|master)
    npm run lint && npm run format:check && npm run build
    ;;
  *)
    echo "Skip pre-push checks on $BRANCH"
    ;;
esac

